### ISSUE TITLE
[workflow] add something to the governance doc about how to become a maintainer

### ISSUE THREAD

**Issue by duglin** [cncf/wg-serverless#116]
The docs at: https://github.com/cncf/wg-serverless/tree/master/workflow/spec/governance  are a good start but now let's add something in there about how someone can become a "maintainer". People will want to see a clear path to a leadership role.

**Comment by salaboy** [comment]
@duglin perfect, we should add some times into that document as well, to make sure that PRs are not inactive for long period of times. 
It will be interesting for the group also to see how people can become an OWNER, by nomination, relevance or merit. If you are an OWNER and not reviewing PRs, due lack of time, personal problems, or not enough background to review, it will be great to have a process to also step down.

**Comment by duglin** [comment]
Yup - all good things to include in the docs

**Comment by tsurdilo** [comment]
@duglin @salaboy hi guys, take a look at https://github.com/cncf/wg-serverless/pull/120 .. this is my first attempt so all inputs more than welcome. thanks

**Comment by tsurdilo** [comment]
https://github.com/cncf/wg-serverless/pull/120 was merged. I will close this issue. Please reopen it if you think changes are still needed for this. Thanks!
