### ISSUE TITLE
restructure the event state and operation state

### ISSUE THREAD

**Issue by cathyhongzhang** [cncf/wg-serverless#141]
Here is my thought to address the confusion on the event state: 
We can do the following to make it more clear and more consistent with the definition of other states, especially consistency with the Operation state
1. rename the "events" field to "eventAction" since the definition of "events" includes not only event triggers, but also actions and action mode association with the event triggers, and the transition to next state.  Suggestion for a better name is welcomed. 
2. Add "operationAction" to operation state and move "actionMode" and "actions" inside "operationAction". This will make the first level fields of all the states be more consistent.
3. Modify the "condition" definition inside existing "events" as follows:
   "Condition consisting of Boolean operation of events that will trigger the actions"
   I guess existing description that says "Condition consisting of Boolean operation of events that will trigger the event state" could cause confusion. If the event state is not the start state, the previous state transition triggers transition to the event state, not the events. 

wdyt?

**Comment by tsurdilo** [comment]
@cathyhongzhang here are changes i did based on your info here: https://github.com/cncf/wg-serverless/pull/142

1. called the parameter "onReceive"
2. this just brings another layer of json definition which imo is not needed for operation state. didnt do this
3. updated to "Condition matching a received event with one or more defined triggers"

**Comment by cathyhongzhang** [comment]
The reason of bringing another layer of json is to make the first level of state definition to be consistent among all the states. If you look at the first level definition of Event state, switch state etc. all have two levels of definition, except operation state. But I do not have a strong opinion on this.

**Comment by tsurdilo** [comment]
Can be closed as https://github.com/cncf/wg-serverless/pull/142 is merged
