### ISSUE TITLE
Transition precedence with the retry definition

### ISSUE THREAD

**Issue by manuelstein** [cncf/wg-serverless#164]
Transitions are a great way to specify that the workflow should switch to another state. But I think there's a problem with the retry definition allowing to define transitions.

Currently, transitions can be specified 
- in onError behaviour of (1) workflow runtime errors, (2) delay- (3) event- (4) operation- (5) parallel- (6) switch- (7) subflow- and (8) foreach-state
- in eventactions to evaluate at the end of a sequence or parallel set of actions as part of the event state
- in states to define where next to transition to (delay, operation, parallel, subflow, relay, foreach and switch state) and in switch not only as default but also for single- and- or- and not-choices

and also:
- in retry behaviour of a single action

I'm especially concerned with the latter in concurrent actions. Any parallel state or an event state that uses parallel mode IIUC may contain such an action retry definition, that, when the maximum number of retries has been exceeded, transitions out of the branch into a state that, e.g. halts the workflow. When the retry policy fires, i.e. it says that it is time to transition, the parallel state could no longer wait until completion of all the parallel actions. It is undefined what happens to the ongoing concurrent executions.

Unlike the retry (that is attached to an action) there is no problem with onError, because error definitions are only used for the outcome of the entire state or for overall workflow runtime errors. But retry is tied to an action, which can happen anywhere during a more complex state execution.

I see a several ways to resolve this:

1. specify that an overrun of attempts is an error, i.e. halt or conclude executions within the state to ensure completion and then trigger the state's onError behaviour
2. specify that in case of exceeding maxAttempts, the surrounding state would still conclude (join parallel executions) but that the retry transition overwrites any other evaluation, i.e. a preceding retry transition overrules any other outcome of the state.
3. let the parallel branch enter that state and be generally aware of branching in the workflow

For a clean workflow state handling, I'd prefer **1.** because exceeding retries to me are an error and circumventing the state's onError definition with an in-place retry transition can be a bit confusing.
I'm tempted towards **3.**, i.e. to allow branching/concurrent paths in the workflow. As of now, concurrency can only happen within a state. Even multiple arriving events that correlate to the same workflow instance can not preempt/interrupt the flow but would be buffered and hence may actually never be consumed. At least I think the current positions in this group are not to allow a workflow to take concurrent paths. Branching out and aggregating branches at a later point would be a bit more powerful, but can also make it a lot more complex.

On a related note, I'd like to point out the choice state; by using a fitting expressionLanguage transitions allow similar matching of event data and can achieve the same boolean logic and value comparisons that are currently defined as choices, which sort of makes the choice state superfluous.

**Comment by tsurdilo** [comment]
Good points. I will look into merging onError and retry definitions to work together. This should solve most of the issues provided. Thanks!

**Comment by tsurdilo** [comment]
@manuelstein here we go: https://github.com/cncf/wg-serverless/pull/166

Regarding the comments on switch state - could you raise a separate issue for it please? thanks.

**Comment by manuelstein** [comment]
Thanks for preparing PR and merging changes. The issue is resolved, closing.
