### ISSUE TITLE
[workflow] separating consumed/produced event types

### ISSUE THREAD

**Issue by manuelstein** [cncf/wg-serverless#186]
__Status:__ A workflow description has an events property, a set of CloudEvent definitions that can be "consumed or produced". Each event definition has a mandatory source and type in accordance with CloudEvents.

__Issue:__ It is difficult to identify the ones produced and the ones consumed. An engine that acts as the producer would need to ensure that all created events' source+ID pairs are unique, e.g. by putting itself as source. An engine may want to register as consumer of consumed event types only.
__Should the spec separate produced/consumed event types?__

_Also, for the types produced, what would be used as source?_
The developer can statically set an absolute URI and would somehow need to ensure all produced events' IDs are unique (UUIDs are typically reliable). Or would the workflow engine want to put its own absolute URI to identify as the source of an event?

**Comment by tsurdilo** [comment]
** Should the spec separate produced/consumed event types? ** - I would say no for now. Reason being is an even can be both consumed and produced if needed.

The source of produced events should be determined by the implementation which is actually going to produce it. I don't think this should be part of the workflow definition. Good point tho as that is something we should add to the documentation. I will create pr.
