### ISSUE TITLE
[workflow] Check/Verify relative + absolute links in specification docs

### ISSUE THREAD

**Issue by tsurdilo** [cncf/wg-serverless#198]
* [examples.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/examples.md)
* [extending.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/extending.md)
* [readme.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/readme.md)
* [references.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/references.md)
* [roadmap.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/roadmap.md)
* [spec.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/spec.md)
* [usecases.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/usecases.md)

**Comment by stevecrozz** [comment]
Can you clarify what this task is about? You just want someone to click all the links in the above pages and ensure they work properly?

**Comment by tsurdilo** [comment]
Yes, just to validate all links work.

**Comment by SwEngin** [comment]
would like to look into this

**Comment by SwEngin** [comment]
So I checked all the links and that was the result:

- [extending.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/extending.md) doesn't contain any links
- In [references.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/references.md) link to Huawei FunctionGraph workflow definition  is broken should be https://support.huaweicloud.com/en-us/productdesc-functiongraph/functiongraph_01_0100.html instead
- In [roadmap.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/roadmap.md#v01-released-april-1-2020) all links to spec under version 0.1 should point to spec in 0.1 branch
- In [roadmap.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/roadmap.md#v01-released-april-1-2020) Prepare github branch and docs for v0.1 may be a link to the branch in the comments is missing
- In [roadmap.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/roadmap.md#v02-release-data-tbd)  Rename Relay to Inject state broken link in comments

**Comment by tsurdilo** [comment]
Thank you @SwEngin !

**Comment by tsurdilo** [comment]
https://github.com/cncf/wg-serverless/pull/231

**Comment by tsurdilo** [comment]
Commit - https://github.com/cncf/wg-serverless/commit/24e77e90c96ceac8432880a471948efbd543cca6
Thanks again!
