### ISSUE TITLE
[workflow] Verify all examples code against the latest JSON Schema

### ISSUE THREAD

**Issue by tsurdilo** [cncf/wg-serverless#199]
* [examples.md](https://github.com/cncf/wg-serverless/blob/master/workflow/spec/examples.md)

**Comment by stevecrozz** [comment]
Done. All the workflow definitions from the examples file conform to: https://raw.githubusercontent.com/cncf/wg-serverless/master/workflow/spec/schema/serverless-workflow-schema.json

If you want to put together a CI system, like travis-ci for example, I could probably write a script to automate this validation...

**Comment by tsurdilo** [comment]
Thank you @stevecrozz !!

I think automating this would be great - we are currently waiting on the approval of our sandbox proposal - https://github.com/cncf/toc/pull/376. If approved I think we will be able to have a specific github repository for the specification and your help with setting all this up would be really great to have! We could do it now but I just worry we would have to do it on new repo again. wdyt?

**Comment by tsurdilo** [comment]
Solved by @stevecrozz . Will close. Thanks again!
