### ISSUE TITLE
Is cron like scheduling possible?

### ISSUE THREAD

**Issue by singhkays** [cncf/wg-serverless#245]
I've been reviewing the spec and it seems like you can define the state/task start kind to be scheduled but this only takes an interval as a property. Is it possible to specify a cron like syntax?

**Comment by tsurdilo** [comment]
@singhkays the schedule start interval prop currently is expected to use the ISO 8601 date and time format. 
The specification "Schedule Definition" shows 4 different ways you can use it to define.
ISO 8601 also has a repeating interval definition which you can use.

Could you please show an example where ISO 8601 does not fit your needs and lets add it :) 

Also if you don't mind please, we are in the process to moving to our new github repo : 
https://github.com/cncf/wg-serverless-workflow
and if you don't mind lets move this conversation there if possible as a new issue ? 
Thanks!

**Comment by tsurdilo** [comment]
Moved to new repo - https://github.com/cncf/wg-serverless-workflow/issues/31
