### ISSUE TITLE
add Algorithmia for Serverless AI?

### ISSUE THREAD

**Issue by doppenhe** [cncf/wg-serverless#39]
https://algorithmia.com/serverless-ai-layer

**Comment by duglin** [comment]
@doppenhe where did you want this added? Could you open a PR with the exact edits you're looking for?

**Comment by leecalcote** [comment]
@doppenhe I assume you're looking for an addition of Algorithmia in the Landscape?... in the platforms layer?

**Comment by doppenhe** [comment]
I think in the platforms layer. Filling out the required docs now and will 
submit PR. 

Diego M. Oppenheimer
CEO - Algorithmia
Tel: (646) 598-4099
http://Algorithmia.com <http://www.algorithmia.com/>
diego@algorithmia.com
blog.algorithmia.com
@doppenhe <http://twitter.com/doppenhe>

**Comment by duglin** [comment]
Closing this since they're in the landscape spreadsheet now.
