### ISSUE TITLE
Fix image used for the Fission FaaS platform

### ISSUE THREAD

**Issue by erwinvaneyk** [cncf/wg-serverless#41]
The landscape contains a logo for "platform9" under "platform > kubernetes-native". However, Platform9 is the company contributing to the FaaS platform **Fission**. So it might be better to change the logo to one of Fission. For example:

![image](https://user-images.githubusercontent.com/2803726/36433042-e85a0228-165b-11e8-9185-3c706acdad13.png)

Or see: http://fission.io or https://github.com/fission/fission

**Comment by leecalcote** [comment]
@erwinvaneyk yes, agreed.

**Comment by erwinvaneyk** [comment]
Thanks for fixing this!
