### ISSUE TITLE
Workstream Proposal: CE Client SDK

### ISSUE THREAD

**Issue by duglin** [cncf/wg-serverless#59]
See: https://github.com/cloudevents/spec/issues/205

- - -
Please discuss, then vote with a 👍 if you would like this to be the next workstream item.

**Comment by matzew** [comment]
Simple API / Java interface. Based on the `0.1` spec:
https://github.com/project-streamzi/jcloudevents/blob/master/src/main/java/io/streamzi/cloudevents/CloudEvent.java

**Comment by duglin** [comment]
This issue was opened so we could leverage github's voting/comment feature to determine which work item to focus on next. Since the vote is over, the issue will now be closed - but closing it has no effect on whether we address it in the future or not. The list of potential work items can still be found at: https://github.com/cncf/wg-serverless/tree/master/proposals

**Comment by matzew** [comment]
FWIW. the repo is now here: 

https://github.com/cloudevents/sdk-java
