### ISSUE TITLE
[workflow] Define event-expression format

### ISSUE THREAD

**Issue by ruromero** [cncf/wg-serverless#87]
We need to define how the `event-expression` must be expressed. Trying to keep it language-agnostic.

#### Comparison
* `eq`: equals
* `ne`: not equals
* `empty`: If the value is empty or doesn't exist

#### Logical
* `and`: And operator
* `or`: Or operator
* `not`: Not operator

### Examples

```
name eq 'mytrigger'
type eq 'sometype' or type ne 'uglytype'
not empty(correlation_token)
```

**Comment by ad-m** [comment]
What about [Common Expression Language (CEL)](https://github.com/google/cel-spec)?

**Comment by tsurdilo** [comment]
@ruromero @ad-m the event expression evaluation is an implementation detail.
Implementors can chose for example:
* SPEL 
* JEXL
* MVEL
* Rule engine Evaluation
* etc

We should not force an implementation here at all, but leave it as a simple string value and let implementors decide what expression languages they support or not.

**Comment by ruromero** [comment]
If we want this to be portable between implementations we must specify how to express conditions formally. Otherwise expressions won't work across different implementations.

I agree it could be an existing one. If we decide to support more than one, then there has to be a way to say which one is being used.

e.g.
```
event-expression: "spel: <expression>"
```

I consider this adds complexity and verbosity therefore I prefer to choose one that suits our needs that is not related to any specific programming language. As seen, it doesn't need to be very sophisticated.

The ones proposed by @tsurdilo are Java specific but I am not aware of any popular expression language with implementations of the most common programming languages.

The one mentioned by @ad-m only has cpp and go implementations.

A possible solution would be to define what the expression language used by the implementation must support as in my initial comment and let each spec implementation to pick any expression language implementation that supports this minimum set of operations.

WDYT?

**Comment by bluemonk3y** [comment]
My preference would be to follow SQL as closely as possible. It has universal acceptance and standards.

**Comment by tsurdilo** [comment]
I don't think the specification can say which languages to support or not, but agree that language field if you want can be declared, as is already for example done in bpmn2. So you could have:
```
"expression": {
    "language": "spel",
    "body": "expression-str"
}
```

Note that you should then make the language parameter optional and add it also part of the workflow def parameters, as user might want to use the same language throughout the workflow, and it would be overkill to have to specify it on every expression.

**Comment by tsurdilo** [comment]
fixed via pr https://github.com/cncf/wg-serverless/pull/113. closing.
