### ISSUE TITLE
[workflow] Event state simplification

### ISSUE THREAD

**Issue by ruromero** [cncf/wg-serverless#88]
Event states can just be the entrypoint for a workflow. There is no need to define any actions and just define the `next-state` which might be an `OPERATION` or something else.

e.g.

```
    {
      "name": "test-state",
      "events": [
        {
          "event-expression": "name eq event1",
          "timeout": "10 min",
          "next-state": "nextStateForEvent1"
        },
        {
          "event-expression": "name eq event2",
          "timeout": "10 min",
          "next-state": "nextStateForEvent2"
        }
      ],
      "type": "EVENT",
      "start": true
    },
```

**Comment by tsurdilo** [comment]
@ruromero so then it would be a switch state?

**Comment by ruromero** [comment]
@tsurdilo is not exactly a switch. It has the concept of timeout and can access the event metadata like name, type, source, correlation_token. The switch uses the payload for decisions.

**Comment by tsurdilo** [comment]
@ruromero I'm pretty sure you can already have the shown json as its currently defined (just remove actions and action-mode from required params of Action Definition)?  
I still think that the way it looks a switch state should be the appropriate state to do this logic tho if possible.

**Comment by tsurdilo** [comment]
I think that you proposed a different approach in https://github.com/cncf/wg-serverless/pull/105.
We can close this and comment on that PR regarding proposed changes imo. Closing.
